### ISSUE TITLE
add ipv6 configuration by default

### ISSUE THREAD

**Issue by contactwajeeh** [WeeJeWel/wg-easy#29] opened 2021-06-07 02:07 UTC
Is there a way to include ipv6 configuration by default

**Comment by markuman** [comment] 2021-06-29 09:53
https://github.com/WeeJeWel/wg-easy/issues/34

**Comment by markuman** [comment] 2021-06-29 09:57
Basically for ingress, you need to make your container (docker-proxy) also bind ipv6.

``ỳml
    ports:
      - "[::]:51820:51820/udp"
      - "51820:51820/udp"
      - "51821:51821/tcp"
```  

Can be verified with

```
$ sudo netstat -tulpn|grep docker-proxy
tcp        0      0 0.0.0.0:51821           0.0.0.0:*               LISTEN      1292/docker-proxy   
udp        0      0 0.0.0.0:51820           0.0.0.0:*                           1309/docker-proxy   
udp6       0      0 :::51820                :::*                                1297/docker-proxy   
```

Egress is more difficult

* https://michael.stapelberg.ch/posts/2018-12-12-docker-ipv6/
* https://community.hetzner.com/tutorials/docker-ipv6-securely
* https://iambenmitchell.medium.com/hetzner-public-ipv4-and-ipv6-subnet-routing-with-docker-5bd534e4b8b1
* https://github.com/robbertkl/docker-ipv6nat


In case of ipv6 is would be much easier when wg-easy is also easy to install it nativley without docker on a plain ubuntu 20.04 vm.

**Comment by WeeJeWel** [comment] 2021-07-13 19:04
Duplicate of #34

**Closed by WeeJeWel** 2021-07-13 19:04 UTC

**Comment by markuman** [comment] 2021-07-13 19:05
Why closing the older issue with more relevant informations?

**Comment by WeeJeWel** [comment] 2021-07-13 19:06
I tossed a coin, sorry.
