### ISSUE TITLE
Ipv6 only VPS

### ISSUE THREAD

**Issue by dibu28** [WeeJeWel/wg-easy#316] opened 2022-07-13 10:09 UTC
Hello.
Can I use ipv6 only VPS for wg-easy?
Can you please tell me how to modify docker settings for it to work?
And will it work with mobile and desktop clients?

**Comment by petefree1** [comment] 2022-08-08 09:48
Hello, I am also interested in this question. how to set up ipv6 on vps

**Comment by dibu28** [comment] 2022-08-21 19:40
@petefree1 Some VPS hosters have cheapest ipv6 only plans.
Like here $2.5mo VPS https://www.vultr.com/pricing/
So I wonder if I can use it for WireGuard and wg-easy.

**Comment by WeeJeWel** [comment] 2022-08-25 19:01
Duplicate of #138

**Closed by WeeJeWel** 2022-08-25 19:01 UTC
