### ISSUE TITLE
web UI lags as hell

### ISSUE THREAD

**Issue by cuzrawr** [WeeJeWel/wg-easy#294] opened 2022-06-20 06:53 UTC
Web UI close to unresponsive due to huge lags when there a lot of clients.
Creation or even push buttons to disable clients takes an unreasonable amount of time.

![lags](https://user-images.githubusercontent.com/46599814/174542065-b795e6f2-fc10-4957-bbf1-9a1c02b33bdb.png)

wg-easy version - docker:nightly ( updated 1 min ago ).

**Comment by eandersons** [comment] 2022-06-20 06:59
Seems like a duplicate of #261 of #287 and possibly related to #195.

**Comment by cuzrawr** [comment] 2022-06-20 07:40
Here video proof of lags:

https://user-images.githubusercontent.com/46599814/174549867-934a4b01-d178-422d-92f6-414ed2423c6a.mp4

**Comment by thepheer** [comment] 2022-06-23 11:06
Yeah, and as I already said in some of the duplicate issues:

> I really like this project, for my use case it's perfect in every way, but I'd say this chart library just has to be removed completely. It seems it was never intended to be used for realtime charts and there's no way to make it fast enough for this purpose. At least this is my conclusion from a brief investigation of the issue.

**Comment by WeeJeWel** [comment] 2022-06-23 11:09
Meh :(

If anyone wants to create a PR that switches to MetricsGraphics, please go ahead.

**Comment by thepheer** [comment] 2022-06-23 11:14
I might try on this weekend if I have time (no promises tho). 👀

**Comment by WeeJeWel** [comment] 2022-06-25 20:41
I've replaced ApexCharts with my own `<div>` implementation. Does this work better? https://github.com/WeeJeWel/wg-easy/commit/faf00d46d9a15ffa519cc87a9eedc36ed28c4ddf

It's available on DockerHub, just still with tag `v6`.

**Comment by vitasha10** [comment] 2022-06-25 20:46
Is it possible to upgrade to this version with an existing container?

**Comment by thepheer** [comment] 2022-06-25 23:06
@WeeJeWel with 35 clients (only a few of them active) there's no lags at all. Great job!

**Comment by WeeJeWel** [comment] 2022-06-26 06:26
Nice, I'll release it as v7 later today.

**Closed** 2022-06-26 09:30 UTC

**Comment by WeeJeWel** [comment] 2022-06-26 09:31
This is now fixed. Please consider [donating](https://github.com/sponsors/WeeJeWel/) to support the development of wg-easy.
